### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by drzraf** [phpactor/code-transform#31]
Seems there is none, and it's hard to start using phpactor code-transform without it.
Even on a deductive _best-effort_ trying to use it to rename a variable is quite hard:
* `./bin/phpactor config:dump | grep transform`
* `./bin/phpactor help class:transform`
* `cat doc/configuration.md`
* `echo "code_transform.refactor.rename_variable:  ~" > phpactor/.phpactor.yml`
* `config:dump => "code_transform.refactor.rename_variable" are not known`

=> Renaming variables is a **frequent** refactoring => **Command**: _RPC only_

**Comment by dantleech** [comment]
Are you trying to use this library independently, or are you trying to rename a variable with Phpactor?

Phpactor supports variable renaming via. RPC. The VIM plugin uses RPC to communicate with PHpactor. For the end-user the context menu provides access top this functionality.

**Comment by dantleech** [comment]
If this is not a library issue, please cfreate an issue on https://github.com:phpactor/phpactor for any problems regarding the documentation.

**Comment by drzraf** [comment]
Since it's RPC only I'm now using this helper:
```php
<?php

$file = "my-file.php";
print(
  json_encode(
    [
      "action" => "transform",
      "parameters" => [
        "source" => file_get_contents($file),
        "path" => $file,
        "transform" => "rename_variable"
      ]
    ]
  )
);
```

`php renamer.php | ./bin/phpactor rpc`
`"message": "Generator \"refactor.rename_variable\" not known, known elements: \"complete_constructor\", \"implement_contracts\", \"fix_namespace_class_name\", \"add_missing_properties\""`

Even then:
```php
$container->register('code_transform.refactor.rename_variable', function (Container $container) {
            return new TolerantRenameVariable();
        }
```

does not seem to register a RPC command.


And deeper: `lib/Adapter/TolerantParser` do not implement a (registerable) `Transformer`

The overall issue is about : **how** to use the software to output a version of a file renaming one variable. And whether it's the `code-transform` repository or `lib/Extension/CodeTransformExtra/` phpactor is unknown to me.


/edit
Started getting something with:
```php
<?php

$file = "file.php";
print(
  json_encode(
    [
      "action" => "rename_variable",
      "parameters" => [
        "source" => file_get_contents($file),
        "path" => $file,
        "scope" => "file",
        "name" => "var",
        "offset" => "0"
      ]
    ]
  )
);
```

thanks to [emacs-mode](https://github.com/emacs-php/phpactor.el/blob/b69f2d9b2490c26c782d327344a54c19b5142cb3/phpactor.el#L738)
... to find that even at it's more internal level, the API relies on `($source, $offset, $newName)` instead of `($source, $oldName, $newName)`.

**Comment by dantleech** [comment]
If you want to use this library (which isn't stable, and could break at any time) you can do something like:

```
<?php
use Phpactor\CodeTransform\Domain\SourceCode;

$sourceCode = SourceCode::fromString(file_get_contents('yourphp.php'));
$renamer = new TolerantRenameVariable();
$renamer->renameVariable($sourceCode, $offset, $newName);
```

You can see this being used directly here: https://github.com/phpactor/phpactor/blob/develop/lib/Extension/CodeTransformExtra/Rpc/RenameVariableHandler.php

Note that this library is supporting Phpactor - it's not necessarily meant for general consumption - but if you find it useful, let me know.

**Comment by drzraf** [comment]
Thank you, that's way better boilerplate!

Could you please add any reference-code for listing variables (and their offset) in a given sourcecode ?
I tried:
```php
$sc = Phpactor\ClassMover\Domain\SourceCode::fromString(
$finder = (new TolerantClassFinder())->findIn($sc); /// + getIterator()
```

But these are only `references` (not symbols).
Maybe `TolerantSourceCodeReflector.php` is a better fit but it sounds harder to instantiate.

**Comment by dantleech** [comment]
This is the job of another library: [Worse Reflection](https://github.com/phpactor/worse-reflection).

In a nutshell:

```php
use Phpactor\WorseReflection\ReflectorBuilder;

$localVariables = ReflectorBuilder::create()
    ->addSource($sourceCode)
    ->build()
     ->reflectOffset($source, strlen($source)) // or whatever position in the file you want to analyse
     ->frame()->locals();
```
That will reflect the "frame" at the given character offset in a file. There are lots of other options there for reflecting classes etc.

**Comment by drzraf** [comment]
Thanks to this I could move forward!
The two main things I missed are:
1. A `renameVariable($source, $oldName, $newName)` API
Because it would be very useful for external tools (unlike interactive editors)

2. A `multiRenameVariable($source, [$oldName => $newName])` API
Because renaming once change the offsets in the what would forces any iterative use to have to search again using a refreshed sourceCode.

**Comment by drzraf** [comment]
A last question anyway: I could not find how to remove a node (class, method, trait, parameter, ...). Is this something implemented?
